#ifndef __HW_FLAGS_H
#define __HW_FLAGS_H

#define DFII_CONTROL_SEL		0x01
#define DFII_CONTROL_CKE		0x02
#define DFII_CONTROL_ODT		0x04
#define DFII_CONTROL_RESET_N	0x08

#define DFII_COMMAND_CS		0x01
#define DFII_COMMAND_WE		0x02
#define DFII_COMMAND_CAS	0x04
#define DFII_COMMAND_RAS	0x08
#define DFII_COMMAND_WRDATA	0x10
#define DFII_COMMAND_RDDATA	0x20


#endif /* __HW_FLAGS_H */